/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UmkmRouteImport } from './routes/umkm'
import { Route as ProfilTimRouteImport } from './routes/profil-tim'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as MapRouteImport } from './routes/map'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KampungIndexRouteImport } from './routes/kampung.index'
import { Route as KampungSlugRouteImport } from './routes/kampung.$slug'

const UmkmRoute = UmkmRouteImport.update({
  id: '/umkm',
  path: '/umkm',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilTimRoute = ProfilTimRouteImport.update({
  id: '/profil-tim',
  path: '/profil-tim',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KampungIndexRoute = KampungIndexRouteImport.update({
  id: '/kampung/',
  path: '/kampung/',
  getParentRoute: () => rootRouteImport,
} as any)
const KampungSlugRoute = KampungSlugRouteImport.update({
  id: '/kampung/$slug',
  path: '/kampung/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/map': typeof MapRoute
  '/profil': typeof ProfilRoute
  '/profil-tim': typeof ProfilTimRoute
  '/umkm': typeof UmkmRoute
  '/kampung/$slug': typeof KampungSlugRoute
  '/kampung/': typeof KampungIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/map': typeof MapRoute
  '/profil': typeof ProfilRoute
  '/profil-tim': typeof ProfilTimRoute
  '/umkm': typeof UmkmRoute
  '/kampung/$slug': typeof KampungSlugRoute
  '/kampung': typeof KampungIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/map': typeof MapRoute
  '/profil': typeof ProfilRoute
  '/profil-tim': typeof ProfilTimRoute
  '/umkm': typeof UmkmRoute
  '/kampung/$slug': typeof KampungSlugRoute
  '/kampung/': typeof KampungIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/map'
    | '/profil'
    | '/profil-tim'
    | '/umkm'
    | '/kampung/$slug'
    | '/kampung/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/map'
    | '/profil'
    | '/profil-tim'
    | '/umkm'
    | '/kampung/$slug'
    | '/kampung'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/map'
    | '/profil'
    | '/profil-tim'
    | '/umkm'
    | '/kampung/$slug'
    | '/kampung/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  MapRoute: typeof MapRoute
  ProfilRoute: typeof ProfilRoute
  ProfilTimRoute: typeof ProfilTimRoute
  UmkmRoute: typeof UmkmRoute
  KampungSlugRoute: typeof KampungSlugRoute
  KampungIndexRoute: typeof KampungIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/umkm': {
      id: '/umkm'
      path: '/umkm'
      fullPath: '/umkm'
      preLoaderRoute: typeof UmkmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil-tim': {
      id: '/profil-tim'
      path: '/profil-tim'
      fullPath: '/profil-tim'
      preLoaderRoute: typeof ProfilTimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kampung/': {
      id: '/kampung/'
      path: '/kampung'
      fullPath: '/kampung/'
      preLoaderRoute: typeof KampungIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kampung/$slug': {
      id: '/kampung/$slug'
      path: '/kampung/$slug'
      fullPath: '/kampung/$slug'
      preLoaderRoute: typeof KampungSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  MapRoute: MapRoute,
  ProfilRoute: ProfilRoute,
  ProfilTimRoute: ProfilTimRoute,
  UmkmRoute: UmkmRoute,
  KampungSlugRoute: KampungSlugRoute,
  KampungIndexRoute: KampungIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
